// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdfdZzI3C6Dj67-efwiUiYG7rRnPLRcPI',
    appId: '1:851087939729:web:fdfb6b59b31deb1c784730',
    messagingSenderId: '851087939729',
    projectId: 'notiee-1a56a',
    authDomain: 'notiee-1a56a.firebaseapp.com',
    storageBucket: 'notiee-1a56a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm3y3jEpgX1q1wu57ct8J0C097lIdkqTg',
    appId: '1:851087939729:android:d057e94b9bda39b7784730',
    messagingSenderId: '851087939729',
    projectId: 'notiee-1a56a',
    storageBucket: 'notiee-1a56a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOde6NbYXwwxm0CEVMR_TPNy8dtPPepU4',
    appId: '1:851087939729:ios:f9e3abea22cfae67784730',
    messagingSenderId: '851087939729',
    projectId: 'notiee-1a56a',
    storageBucket: 'notiee-1a56a.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOde6NbYXwwxm0CEVMR_TPNy8dtPPepU4',
    appId: '1:851087939729:ios:f9e3abea22cfae67784730',
    messagingSenderId: '851087939729',
    projectId: 'notiee-1a56a',
    storageBucket: 'notiee-1a56a.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdfdZzI3C6Dj67-efwiUiYG7rRnPLRcPI',
    appId: '1:851087939729:web:81aa1c12af213e63784730',
    messagingSenderId: '851087939729',
    projectId: 'notiee-1a56a',
    authDomain: 'notiee-1a56a.firebaseapp.com',
    storageBucket: 'notiee-1a56a.firebasestorage.app',
  );
}
